[project]
name = "qgis-plugin-tianditu"
version = "0.5.0"
description = "QGIS 天地图工具，方便进行天地图瓦片底图的添加以及简单实现了部分天地图 Web 服务 API（地名搜索、地理编码查询、逆地理编码查询） "
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyqt6>=6.8.1",
]
