name: 'Commit CI'

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    name: 'build'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.0"

      - name: Set up Python
        run: uv python install

      - name: 'Build and Pack'
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.zip