name: "Commit CI"

on:
  push:
    branches:
      - "dev"

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install just
        uses: extractions/setup-just@v4

      - name: Set up Python
        run: uv python install

      - name: Analysing the code with pylint
        run: just lint

      - name: "Build and Pack"
        run: just pack

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          # name: "tianditu_tools"
          path: ./dist/*.zip
          archive: false
