name: 'Release'

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.0"

      - name: Set up Python
        run: uv python install

      - name: 'Build and Pack'
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Create GitHub release
        id: release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ github.ref_name }} ./dist/*.zip -t "Release ${{ github.ref_name }}" --generate-notes -d